### ISSUE TITLE
create another repo for code & etc...

### ISSUE THREAD

**Issue by YontiLevin** [NLPH/NLPH#15]
talked about it in the end of the meeting
please open a new repo for code
and another one for data
so we can separate the meeting protocols from the real working repos

**Comment by YontiLevin** [comment]
@shaypal5

**Comment by yotammanor** [comment]
@YontiLevin sure!
But can you be more specific? It's better that a code-repo corresponds to a specific project (i.e a thing you can deploy somewhere and use it). Which one(s) do we need to start with?

**Comment by YontiLevin** [comment]
task 4 on the list - NLPH python tools
and another one - NLPH dataset

**Comment by yotammanor** [comment]
@YontiLevin sent you an invite to the github org, you should be able to create new repos. Just make sure to add good descriptions to those you create :)

**Comment by YontiLevin** [comment]
Aye aye, captain
